name: Frontend build

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  workflow_dispatch:
    
env:
  LONG_IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4

      - name: Установка короткого хеша
        run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Логин в GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Приведение имени репозитория к нижнему регистру
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Проверка переменной с ключом BACKEND_URL
        run: |
          if [[ -z "${{ vars.BACKEND_URL }}" ]]; then
            echo "Ошибка: BACKEND_URL пустая!"
            exit 1
          else
            echo "BACKEND_URL загружена корректно."
          fi

      - name: Сборка и пуш образа frontend
        uses: docker/build-push-action@v5
        with:
            context: frontend
            tags: |
                ghcr.io/${{ env.REPO_NAME }}/date-choice-frontend:latest
                ghcr.io/${{ env.REPO_NAME }}/date-choice-backend:${{ env.IMAGE_TAG }}
            push: true
            cache-from: type=gha
            cache-to: type=gha,mode=max
            build-args: |
              VITE_BACKEND_URL=${{ vars.BACKEND_URL }}
              VITE_ALLOW_FROM=${{ vars.ALLOW_FROM }}
              VITE_ALLOW_TO=${{ vars.ALLOW_TO }}